# Generated by Django 6.0.5 on 2026-05-23 03:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('details', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['name'], name='main_course_name_571435_idx')],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, to='main.group')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.student')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('degree', models.CharField(choices=[('Associate', 'Associate Degree'), ('Bachelor', 'Bachelor Degree'), ('Master', 'Master Degree'), ('PhD', 'PhD Degree'), ('Doctor', 'Doctoral Degree')], db_index=True, help_text='Degree', max_length=100)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('birth_date', models.DateField()),
                ('kpi', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('profession', models.ManyToManyField(to='main.course')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.teacher'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['is_active'], name='main_studen_is_acti_fce72d_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['name'], name='main_teache_name_57fbb8_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['degree'], name='main_teache_degree_6052ec_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['name'], name='main_group_name_b4f31d_idx'),
        ),
    ]
