# Generated by Django 6.0.5 on 2026-05-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='period',
            field=models.CharField(default=9),
            preserve_default=False,
        ),
    ]
