# Generated by Django 6.0.5 on 2026-05-23 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_course_period'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='profession',
            new_name='course',
        ),
    ]
